### ISSUE TITLE
Criar um Contributing.md

### ISSUE THREAD

**Issue by LucianaMarques** [garoa/ChuviscoBot#37]
Criar um Contributing.md, que deverá conter todas as informações necessárias para quem quiser contribuir com o projeto. 

Acho que podemos deixar para fazer assim que tivermos uma versão mais funcional do projeto.

**Comment by felipesanches** [comment]
Ou podemos documentar o processo atual de desenvolvimento e depois ir fazendo adaptações gradativas conforme forem sendo incorporadas novas práticas.

**Comment by felipesanches** [comment]
O processo atual involve:

(1) cadastro de issues
(2) feature branches para implementar features ou corrigir bugs de alguma issue
(3) envio de pull requests
(4) testes de código (que o desenvolvedor pode rodar localmente com `pytest -x --verbose` antes de enviar um pull request
(5) "build" automático no Travis quando é aberto um pull request. Isso faz os testes rodarem no Travis e o GitHub informa se passou ou não.
(6) Após passar nos testes, e se a feature implementada for OK, um pull request pode ser mesclado ao branch master (com a ação "rebase & merge"). Se houver objeções sobre a feature, um pull request pode ser rejeitado, mesmo que passe em todos testes. Nesse caso recomenda-se apresentar as objeções e discuti-las na própria thread do pull request em questão, ou em novas features abertas com esse propósito.

**Comment by felipesanches** [comment]
Além disso, recomenda-se que mensagens de log de commit incluam referência ao número da issue a que se referem, pois isso faz com que o GitHub automaticamente crie links de referência cruzada entre a thread da issue e os commits.

O mesmo vale para a abertura de um pull request. Recomenda-se dizer na descrição algo como: `Esse pull request trata das questões discutidas na issue #24`.

**Comment by LucianaMarques** [comment]
Legal, concordo com tudo o que você comentou, @felipesanches .

Quero acrescentar mais o seguinte:
1) Eu gostaria que esse repositório fosse amigável para quem é novo em contribuições para open-source. Por isso, acho que é importante dar o passo-a-passo de como fazer o fork e depois configurá-lo na máquina local, como fazer uma nova branch, etc (eu costumo achar legal separar por branch as contribuições para cada issue ou enhancement)

2) Podemos expandir o seu item (4) com um passo-a-passo também detalhado

3) Acho que devemos incentivar com que as pessoas contribuam com documentação também, costuma ser uma boa coisa para quem está começando, inclusive. 

Abro um PR logo mais com tudo isso.

**Comment by felipesanches** [comment]
Perfeito! :-D

**Comment by LucianaMarques** [comment]
Eu submeti hoje dois PRs, considerar apenas o no. 42.

Acho que precisa de melhorias em como deixar mais amigável para contribuições de pessoas mais iniciantes. E precisamos dar um jeito de fazer a documentação.

**Comment by felipesanches** [comment]
ok. obrigado!
