### ISSUE TITLE
Responder com imagens/stickers ao comando /status

### ISSUE THREAD

**Issue by felipesanches** [garoa/ChuviscoBot#40]

**Comment by felipesanches** [comment]
https://core.telegram.org/bots/api#sendsticker

**Comment by felipesanches** [comment]
eu li um pouco a API mas fiquei com dúvidas. Se quiser assumir, manda ver. (mas sinta-se à vontade para pedir ajuda se ficar com dúvidas também)

**Comment by LucianaMarques** [comment]
Legal, mas podemos fazer em conjunto também.

**Comment by felipesanches** [comment]
tamo junto! :-D

**Comment by prinewgirl** [comment]
pelo que entendi vc tem que usar arquivos locais como stickers... se for assim, tem que ver qual é a licença do usado pelo bot do rjmunhoz

**Comment by prinewgirl** [comment]
pelo que li pro python-telegram-bot mandar stickers tem que ter um arquivo local que ele coloca dentro de um objeto que cospe os stickers... se for assim me parece muito complicado e ainda tem o problema da licença do sticker usado

**Comment by prinewgirl** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/blob/master/tests/test_sticker.py

**Comment by felipesanches** [comment]
Issue resolvida coletivamente por @prinewgirl, @LucianaMarques e @felipesanches no Garoa: https://garoa.net.br/wiki/ChuviscoBot
