### ISSUE TITLE
Discutir qual a melhor forma de documentação

### ISSUE THREAD

**Issue by LucianaMarques** [garoa/ChuviscoBot#43]
Sobre documentação, acho que o que já discutimos foi fazer uma seção no README.md com explicações sobre o que cada arquivo faz. Acho interessante, apesar de que nesse momento de desenvolvimento mais embrionário pode ser que essa documentação fique obsoleta rápido.

O que eu acho que poderíamos fazer além dessa seção, seria fazer algo com o [Read the Docs](https://readthedocs.org/), já vi em alguns projetos e gostaria de aprender. 

Tem também uma outra ferramenta que chama [sphinx](http://www.sphinx-doc.org/en/master/) que também faz geração para alguns formatos (pdf, latex, etc).

Eu acho que faz sentido gerar a documentação separada do README.md porque pode ser que com o aumento do número de arquivos ou com o tamanho em si dos arquivos seja melhor não poluir muito o arquivo.

**Comment by felipesanches** [comment]
Sim, concordo!

Eu sou (profissionalmente) mantenedor de um projeto de software livre que usa "Read The Docs" e Sphinx. Então, por experiencia própria, posso dar o endosso de que é, de fato, uma solução profissional adotar essas tecnologias!

**Comment by felipesanches** [comment]
já incluímos os arquivos de configuração, mas vou manter aberta a issue enquanto estudamos como fazer o setup do readthedocs pra sincronizar com esse repo.

**Comment by LucianaMarques** [comment]
Falta agora fazer a integração do projeto com o readthedocs

**Comment by LucianaMarques** [comment]
Uma outra coisa a se pensar depois é separar o projeto em versões: estável/stable, master/última versão, etc. Parece que o readthedocs já capta isto automaticamente com nomeação de branches.

https://docs.readthedocs.io/en/latest/versions.html
